#############################################################################
# Makefile for building: Softphone3
# Generated by qmake (3.0) (Qt 5.6.4)
# Project:  Softphone3.pro
# Template: app
# Command: /home/nathan/raspi/qt5/bin/qmake -o Makefile Softphone3.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = /home/nathan/raspi/tools/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian-x64/bin/arm-linux-gnueabihf-gcc
CXX           = /home/nathan/raspi/tools/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian-x64/bin/arm-linux-gnueabihf-g++
DEFINES       = -DQT_DEPRECATED_WARNINGS -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -march=armv8-a -mtune=cortex-a53 -mfpu=crypto-neon-fp-armv8 -mfloat-abi=hard --sysroot=/home/nathan/raspi/sysroot -O2 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -march=armv8-a -mtune=cortex-a53 -mfpu=crypto-neon-fp-armv8 -mfloat-abi=hard --sysroot=/home/nathan/raspi/sysroot -O2 -std=gnu++0x -Wall -W -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -I../raspi/qt5pi/include -I../raspi/qt5pi/include/QtWidgets -I../raspi/qt5pi/include/QtGui -I../raspi/qt5pi/include/QtCore -I. -I. -I../raspi/qt5/mkspecs/devices/linux-rpi3-g++
QMAKE         = /home/nathan/raspi/qt5/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = Softphone31.0.0
DISTDIR = /home/nathan/Softphone3/.tmp/Softphone31.0.0
LINK          = /home/nathan/raspi/tools/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian-x64/bin/arm-linux-gnueabihf-g++
LFLAGS        = -Wl,-rpath-link,/home/nathan/raspi/sysroot/opt/vc/lib -Wl,-rpath-link,/home/nathan/raspi/sysroot/usr/lib/arm-linux-gnueabihf -Wl,-rpath-link,/home/nathan/raspi/sysroot/lib/arm-linux-gnueabihf -mfloat-abi=hard --sysroot=/home/nathan/raspi/sysroot -Wl,-O1 -Wl,-rpath,/usr/local/qt5pi/lib
LIBS          = $(SUBLIBS) -lmysqlcppconn -L/home/nathan/raspi/qt5pi/lib -lQt5Widgets -lQt5Gui -lQt5Core -lGL -lpthread 
AR            = /home/nathan/raspi/tools/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian-x64/bin/arm-linux-gnueabihf-ar cqs
RANLIB        = 
SED           = sed
STRIP         = /home/nathan/raspi/tools/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian-x64/bin/arm-linux-gnueabihf-strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		frame.cpp moc_frame.cpp
OBJECTS       = main.o \
		frame.o \
		moc_frame.o
DIST          = ../raspi/qt5/mkspecs/features/spec_pre.prf \
		../raspi/qt5/mkspecs/common/unix.conf \
		../raspi/qt5/mkspecs/common/linux.conf \
		../raspi/qt5/mkspecs/common/sanitize.conf \
		../raspi/qt5/mkspecs/common/gcc-base.conf \
		../raspi/qt5/mkspecs/common/gcc-base-unix.conf \
		../raspi/qt5/mkspecs/common/g++-base.conf \
		../raspi/qt5/mkspecs/common/g++-unix.conf \
		../raspi/qt5/mkspecs/qdevice.pri \
		../raspi/qt5/mkspecs/features/device_config.prf \
		../raspi/qt5/mkspecs/devices/common/linux_device_pre.conf \
		../raspi/qt5/mkspecs/devices/common/linux_device_post.conf \
		../raspi/qt5/mkspecs/devices/common/linux_arm_device_post.conf \
		../raspi/qt5/mkspecs/qconfig.pri \
		../raspi/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../raspi/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		../raspi/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		../raspi/qt5/mkspecs/modules/qt_lib_core.pri \
		../raspi/qt5/mkspecs/modules/qt_lib_core_private.pri \
		../raspi/qt5/mkspecs/modules/qt_lib_dbus.pri \
		../raspi/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		../raspi/qt5/mkspecs/modules/qt_lib_eglfs_device_lib_private.pri \
		../raspi/qt5/mkspecs/modules/qt_lib_gui.pri \
		../raspi/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		../raspi/qt5/mkspecs/modules/qt_lib_network.pri \
		../raspi/qt5/mkspecs/modules/qt_lib_network_private.pri \
		../raspi/qt5/mkspecs/modules/qt_lib_opengl.pri \
		../raspi/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		../raspi/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		../raspi/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../raspi/qt5/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../raspi/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		../raspi/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		../raspi/qt5/mkspecs/modules/qt_lib_sql.pri \
		../raspi/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		../raspi/qt5/mkspecs/modules/qt_lib_testlib.pri \
		../raspi/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		../raspi/qt5/mkspecs/modules/qt_lib_widgets.pri \
		../raspi/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		../raspi/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		../raspi/qt5/mkspecs/modules/qt_lib_xml.pri \
		../raspi/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		../raspi/qt5/mkspecs/modules/qt_lib_zlib_private.pri \
		../raspi/qt5/mkspecs/features/qt_functions.prf \
		../raspi/qt5/mkspecs/features/qt_config.prf \
		../raspi/qt5/mkspecs/devices/linux-rpi3-g++/qmake.conf \
		../raspi/qt5/mkspecs/features/spec_post.prf \
		../raspi/qt5/mkspecs/features/exclusive_builds.prf \
		../raspi/qt5/mkspecs/features/default_pre.prf \
		../raspi/qt5/mkspecs/features/resolve_config.prf \
		../raspi/qt5/mkspecs/features/default_post.prf \
		../raspi/qt5/mkspecs/features/warn_on.prf \
		../raspi/qt5/mkspecs/features/qt.prf \
		../raspi/qt5/mkspecs/features/resources.prf \
		../raspi/qt5/mkspecs/features/moc.prf \
		../raspi/qt5/mkspecs/features/unix/opengl.prf \
		../raspi/qt5/mkspecs/features/uic.prf \
		../raspi/qt5/mkspecs/features/unix/thread.prf \
		../raspi/qt5/mkspecs/features/file_copies.prf \
		../raspi/qt5/mkspecs/features/testcase_targets.prf \
		../raspi/qt5/mkspecs/features/exceptions.prf \
		../raspi/qt5/mkspecs/features/yacc.prf \
		../raspi/qt5/mkspecs/features/lex.prf \
		Softphone3.pro frame.h main.cpp \
		frame.cpp
QMAKE_TARGET  = Softphone3
DESTDIR       = 
TARGET        = Softphone3


first: all
####### Build rules

$(TARGET): ui_frame.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: Softphone3.pro ../raspi/qt5/mkspecs/devices/linux-rpi3-g++/qmake.conf ../raspi/qt5/mkspecs/features/spec_pre.prf \
		../raspi/qt5/mkspecs/common/unix.conf \
		../raspi/qt5/mkspecs/common/linux.conf \
		../raspi/qt5/mkspecs/common/sanitize.conf \
		../raspi/qt5/mkspecs/common/gcc-base.conf \
		../raspi/qt5/mkspecs/common/gcc-base-unix.conf \
		../raspi/qt5/mkspecs/common/g++-base.conf \
		../raspi/qt5/mkspecs/common/g++-unix.conf \
		../raspi/qt5/mkspecs/qdevice.pri \
		../raspi/qt5/mkspecs/features/device_config.prf \
		../raspi/qt5/mkspecs/devices/common/linux_device_pre.conf \
		../raspi/qt5/mkspecs/devices/common/linux_device_post.conf \
		../raspi/qt5/mkspecs/devices/common/linux_arm_device_post.conf \
		../raspi/qt5/mkspecs/qconfig.pri \
		../raspi/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../raspi/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		../raspi/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		../raspi/qt5/mkspecs/modules/qt_lib_core.pri \
		../raspi/qt5/mkspecs/modules/qt_lib_core_private.pri \
		../raspi/qt5/mkspecs/modules/qt_lib_dbus.pri \
		../raspi/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		../raspi/qt5/mkspecs/modules/qt_lib_eglfs_device_lib_private.pri \
		../raspi/qt5/mkspecs/modules/qt_lib_gui.pri \
		../raspi/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		../raspi/qt5/mkspecs/modules/qt_lib_network.pri \
		../raspi/qt5/mkspecs/modules/qt_lib_network_private.pri \
		../raspi/qt5/mkspecs/modules/qt_lib_opengl.pri \
		../raspi/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		../raspi/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		../raspi/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../raspi/qt5/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../raspi/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		../raspi/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		../raspi/qt5/mkspecs/modules/qt_lib_sql.pri \
		../raspi/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		../raspi/qt5/mkspecs/modules/qt_lib_testlib.pri \
		../raspi/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		../raspi/qt5/mkspecs/modules/qt_lib_widgets.pri \
		../raspi/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		../raspi/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		../raspi/qt5/mkspecs/modules/qt_lib_xml.pri \
		../raspi/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		../raspi/qt5/mkspecs/modules/qt_lib_zlib_private.pri \
		../raspi/qt5/mkspecs/features/qt_functions.prf \
		../raspi/qt5/mkspecs/features/qt_config.prf \
		../raspi/qt5/mkspecs/devices/linux-rpi3-g++/qmake.conf \
		../raspi/qt5/mkspecs/features/spec_post.prf \
		../raspi/qt5/mkspecs/features/exclusive_builds.prf \
		../raspi/qt5/mkspecs/features/default_pre.prf \
		../raspi/qt5/mkspecs/features/resolve_config.prf \
		../raspi/qt5/mkspecs/features/default_post.prf \
		../raspi/qt5/mkspecs/features/warn_on.prf \
		../raspi/qt5/mkspecs/features/qt.prf \
		../raspi/qt5/mkspecs/features/resources.prf \
		../raspi/qt5/mkspecs/features/moc.prf \
		../raspi/qt5/mkspecs/features/unix/opengl.prf \
		../raspi/qt5/mkspecs/features/uic.prf \
		../raspi/qt5/mkspecs/features/unix/thread.prf \
		../raspi/qt5/mkspecs/features/file_copies.prf \
		../raspi/qt5/mkspecs/features/testcase_targets.prf \
		../raspi/qt5/mkspecs/features/exceptions.prf \
		../raspi/qt5/mkspecs/features/yacc.prf \
		../raspi/qt5/mkspecs/features/lex.prf \
		Softphone3.pro \
		../raspi/qt5pi/lib/libQt5Widgets.prl \
		../raspi/qt5pi/lib/libQt5Gui.prl \
		../raspi/qt5pi/lib/libQt5Core.prl
	$(QMAKE) -o Makefile Softphone3.pro
../raspi/qt5/mkspecs/features/spec_pre.prf:
../raspi/qt5/mkspecs/common/unix.conf:
../raspi/qt5/mkspecs/common/linux.conf:
../raspi/qt5/mkspecs/common/sanitize.conf:
../raspi/qt5/mkspecs/common/gcc-base.conf:
../raspi/qt5/mkspecs/common/gcc-base-unix.conf:
../raspi/qt5/mkspecs/common/g++-base.conf:
../raspi/qt5/mkspecs/common/g++-unix.conf:
../raspi/qt5/mkspecs/qdevice.pri:
../raspi/qt5/mkspecs/features/device_config.prf:
../raspi/qt5/mkspecs/devices/common/linux_device_pre.conf:
../raspi/qt5/mkspecs/devices/common/linux_device_post.conf:
../raspi/qt5/mkspecs/devices/common/linux_arm_device_post.conf:
../raspi/qt5/mkspecs/qconfig.pri:
../raspi/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri:
../raspi/qt5/mkspecs/modules/qt_lib_concurrent.pri:
../raspi/qt5/mkspecs/modules/qt_lib_concurrent_private.pri:
../raspi/qt5/mkspecs/modules/qt_lib_core.pri:
../raspi/qt5/mkspecs/modules/qt_lib_core_private.pri:
../raspi/qt5/mkspecs/modules/qt_lib_dbus.pri:
../raspi/qt5/mkspecs/modules/qt_lib_dbus_private.pri:
../raspi/qt5/mkspecs/modules/qt_lib_eglfs_device_lib_private.pri:
../raspi/qt5/mkspecs/modules/qt_lib_gui.pri:
../raspi/qt5/mkspecs/modules/qt_lib_gui_private.pri:
../raspi/qt5/mkspecs/modules/qt_lib_network.pri:
../raspi/qt5/mkspecs/modules/qt_lib_network_private.pri:
../raspi/qt5/mkspecs/modules/qt_lib_opengl.pri:
../raspi/qt5/mkspecs/modules/qt_lib_opengl_private.pri:
../raspi/qt5/mkspecs/modules/qt_lib_openglextensions.pri:
../raspi/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri:
../raspi/qt5/mkspecs/modules/qt_lib_platformsupport_private.pri:
../raspi/qt5/mkspecs/modules/qt_lib_printsupport.pri:
../raspi/qt5/mkspecs/modules/qt_lib_printsupport_private.pri:
../raspi/qt5/mkspecs/modules/qt_lib_sql.pri:
../raspi/qt5/mkspecs/modules/qt_lib_sql_private.pri:
../raspi/qt5/mkspecs/modules/qt_lib_testlib.pri:
../raspi/qt5/mkspecs/modules/qt_lib_testlib_private.pri:
../raspi/qt5/mkspecs/modules/qt_lib_widgets.pri:
../raspi/qt5/mkspecs/modules/qt_lib_widgets_private.pri:
../raspi/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
../raspi/qt5/mkspecs/modules/qt_lib_xml.pri:
../raspi/qt5/mkspecs/modules/qt_lib_xml_private.pri:
../raspi/qt5/mkspecs/modules/qt_lib_zlib_private.pri:
../raspi/qt5/mkspecs/features/qt_functions.prf:
../raspi/qt5/mkspecs/features/qt_config.prf:
../raspi/qt5/mkspecs/devices/linux-rpi3-g++/qmake.conf:
../raspi/qt5/mkspecs/features/spec_post.prf:
../raspi/qt5/mkspecs/features/exclusive_builds.prf:
../raspi/qt5/mkspecs/features/default_pre.prf:
../raspi/qt5/mkspecs/features/resolve_config.prf:
../raspi/qt5/mkspecs/features/default_post.prf:
../raspi/qt5/mkspecs/features/warn_on.prf:
../raspi/qt5/mkspecs/features/qt.prf:
../raspi/qt5/mkspecs/features/resources.prf:
../raspi/qt5/mkspecs/features/moc.prf:
../raspi/qt5/mkspecs/features/unix/opengl.prf:
../raspi/qt5/mkspecs/features/uic.prf:
../raspi/qt5/mkspecs/features/unix/thread.prf:
../raspi/qt5/mkspecs/features/file_copies.prf:
../raspi/qt5/mkspecs/features/testcase_targets.prf:
../raspi/qt5/mkspecs/features/exceptions.prf:
../raspi/qt5/mkspecs/features/yacc.prf:
../raspi/qt5/mkspecs/features/lex.prf:
Softphone3.pro:
../raspi/qt5pi/lib/libQt5Widgets.prl:
../raspi/qt5pi/lib/libQt5Gui.prl:
../raspi/qt5pi/lib/libQt5Core.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile Softphone3.pro

qmake_all: FORCE


all: Makefile $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents frame.h $(DISTDIR)/
	$(COPY_FILE) --parents main.cpp frame.cpp $(DISTDIR)/
	$(COPY_FILE) --parents frame.ui $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_header_make_all: moc_frame.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_frame.cpp
moc_frame.cpp: ../raspi/qt5pi/include/QtWidgets/QMainWindow \
		../raspi/qt5pi/include/QtWidgets/qmainwindow.h \
		../raspi/qt5pi/include/QtWidgets/qwidget.h \
		../raspi/qt5pi/include/QtGui/qwindowdefs.h \
		../raspi/qt5pi/include/QtCore/qglobal.h \
		../raspi/qt5pi/include/QtCore/qconfig.h \
		../raspi/qt5pi/include/QtCore/qfeatures.h \
		../raspi/qt5pi/include/QtCore/qsystemdetection.h \
		../raspi/qt5pi/include/QtCore/qprocessordetection.h \
		../raspi/qt5pi/include/QtCore/qcompilerdetection.h \
		../raspi/qt5pi/include/QtCore/qtypeinfo.h \
		../raspi/qt5pi/include/QtCore/qtypetraits.h \
		../raspi/qt5pi/include/QtCore/qisenum.h \
		../raspi/qt5pi/include/QtCore/qsysinfo.h \
		../raspi/qt5pi/include/QtCore/qlogging.h \
		../raspi/qt5pi/include/QtCore/qflags.h \
		../raspi/qt5pi/include/QtCore/qatomic.h \
		../raspi/qt5pi/include/QtCore/qbasicatomic.h \
		../raspi/qt5pi/include/QtCore/qatomic_bootstrap.h \
		../raspi/qt5pi/include/QtCore/qgenericatomic.h \
		../raspi/qt5pi/include/QtCore/qatomic_cxx11.h \
		../raspi/qt5pi/include/QtCore/qatomic_gcc.h \
		../raspi/qt5pi/include/QtCore/qatomic_msvc.h \
		../raspi/qt5pi/include/QtCore/qatomic_armv7.h \
		../raspi/qt5pi/include/QtCore/qatomic_armv6.h \
		../raspi/qt5pi/include/QtCore/qatomic_armv5.h \
		../raspi/qt5pi/include/QtCore/qatomic_ia64.h \
		../raspi/qt5pi/include/QtCore/qatomic_x86.h \
		../raspi/qt5pi/include/QtCore/qatomic_unix.h \
		../raspi/qt5pi/include/QtCore/qglobalstatic.h \
		../raspi/qt5pi/include/QtCore/qmutex.h \
		../raspi/qt5pi/include/QtCore/qnumeric.h \
		../raspi/qt5pi/include/QtCore/qversiontagging.h \
		../raspi/qt5pi/include/QtCore/qobjectdefs.h \
		../raspi/qt5pi/include/QtCore/qnamespace.h \
		../raspi/qt5pi/include/QtCore/qobjectdefs_impl.h \
		../raspi/qt5pi/include/QtGui/qwindowdefs_win.h \
		../raspi/qt5pi/include/QtCore/qobject.h \
		../raspi/qt5pi/include/QtCore/qstring.h \
		../raspi/qt5pi/include/QtCore/qchar.h \
		../raspi/qt5pi/include/QtCore/qbytearray.h \
		../raspi/qt5pi/include/QtCore/qrefcount.h \
		../raspi/qt5pi/include/QtCore/qarraydata.h \
		../raspi/qt5pi/include/QtCore/qstringbuilder.h \
		../raspi/qt5pi/include/QtCore/qlist.h \
		../raspi/qt5pi/include/QtCore/qalgorithms.h \
		../raspi/qt5pi/include/QtCore/qiterator.h \
		../raspi/qt5pi/include/QtCore/qhashfunctions.h \
		../raspi/qt5pi/include/QtCore/qpair.h \
		../raspi/qt5pi/include/QtCore/qbytearraylist.h \
		../raspi/qt5pi/include/QtCore/qstringlist.h \
		../raspi/qt5pi/include/QtCore/qregexp.h \
		../raspi/qt5pi/include/QtCore/qstringmatcher.h \
		../raspi/qt5pi/include/QtCore/qcoreevent.h \
		../raspi/qt5pi/include/QtCore/qscopedpointer.h \
		../raspi/qt5pi/include/QtCore/qmetatype.h \
		../raspi/qt5pi/include/QtCore/qvarlengtharray.h \
		../raspi/qt5pi/include/QtCore/qcontainerfwd.h \
		../raspi/qt5pi/include/QtCore/qobject_impl.h \
		../raspi/qt5pi/include/QtCore/qmargins.h \
		../raspi/qt5pi/include/QtGui/qpaintdevice.h \
		../raspi/qt5pi/include/QtCore/qrect.h \
		../raspi/qt5pi/include/QtCore/qsize.h \
		../raspi/qt5pi/include/QtCore/qpoint.h \
		../raspi/qt5pi/include/QtGui/qpalette.h \
		../raspi/qt5pi/include/QtGui/qcolor.h \
		../raspi/qt5pi/include/QtGui/qrgb.h \
		../raspi/qt5pi/include/QtGui/qrgba64.h \
		../raspi/qt5pi/include/QtGui/qbrush.h \
		../raspi/qt5pi/include/QtCore/qvector.h \
		../raspi/qt5pi/include/QtGui/qmatrix.h \
		../raspi/qt5pi/include/QtGui/qpolygon.h \
		../raspi/qt5pi/include/QtGui/qregion.h \
		../raspi/qt5pi/include/QtCore/qdatastream.h \
		../raspi/qt5pi/include/QtCore/qiodevice.h \
		../raspi/qt5pi/include/QtCore/qline.h \
		../raspi/qt5pi/include/QtGui/qtransform.h \
		../raspi/qt5pi/include/QtGui/qpainterpath.h \
		../raspi/qt5pi/include/QtGui/qimage.h \
		../raspi/qt5pi/include/QtGui/qpixelformat.h \
		../raspi/qt5pi/include/QtGui/qpixmap.h \
		../raspi/qt5pi/include/QtCore/qsharedpointer.h \
		../raspi/qt5pi/include/QtCore/qshareddata.h \
		../raspi/qt5pi/include/QtCore/qhash.h \
		../raspi/qt5pi/include/QtCore/qsharedpointer_impl.h \
		../raspi/qt5pi/include/QtGui/qfont.h \
		../raspi/qt5pi/include/QtGui/qfontmetrics.h \
		../raspi/qt5pi/include/QtGui/qfontinfo.h \
		../raspi/qt5pi/include/QtWidgets/qsizepolicy.h \
		../raspi/qt5pi/include/QtGui/qcursor.h \
		../raspi/qt5pi/include/QtGui/qkeysequence.h \
		../raspi/qt5pi/include/QtGui/qevent.h \
		../raspi/qt5pi/include/QtCore/qvariant.h \
		../raspi/qt5pi/include/QtCore/qmap.h \
		../raspi/qt5pi/include/QtCore/qdebug.h \
		../raspi/qt5pi/include/QtCore/qtextstream.h \
		../raspi/qt5pi/include/QtCore/qlocale.h \
		../raspi/qt5pi/include/QtCore/qset.h \
		../raspi/qt5pi/include/QtCore/qcontiguouscache.h \
		../raspi/qt5pi/include/QtCore/qurl.h \
		../raspi/qt5pi/include/QtCore/qurlquery.h \
		../raspi/qt5pi/include/QtCore/qfile.h \
		../raspi/qt5pi/include/QtCore/qfiledevice.h \
		../raspi/qt5pi/include/QtGui/qvector2d.h \
		../raspi/qt5pi/include/QtGui/qtouchdevice.h \
		../raspi/qt5pi/include/QtWidgets/qtabwidget.h \
		../raspi/qt5pi/include/QtGui/qicon.h \
		../raspi/qt5pi/include/QtWidgets/QPushButton \
		../raspi/qt5pi/include/QtWidgets/qpushbutton.h \
		../raspi/qt5pi/include/QtWidgets/qabstractbutton.h \
		frame.h
	/home/nathan/raspi/qt5/bin/moc $(DEFINES) -I/home/nathan/raspi/qt5/mkspecs/devices/linux-rpi3-g++ -I/home/nathan/Softphone3 -I/home/nathan/raspi/qt5pi/include -I/home/nathan/raspi/qt5pi/include/QtWidgets -I/home/nathan/raspi/qt5pi/include/QtGui -I/home/nathan/raspi/qt5pi/include/QtCore -I/home/nathan/raspi/tools/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian-x64/arm-linux-gnueabihf/include/c++/4.8.3 -I/home/nathan/raspi/tools/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian-x64/arm-linux-gnueabihf/include/c++/4.8.3/arm-linux-gnueabihf -I/home/nathan/raspi/tools/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian-x64/arm-linux-gnueabihf/include/c++/4.8.3/backward -I/home/nathan/raspi/tools/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian-x64/lib/gcc/arm-linux-gnueabihf/4.8.3/include -I/home/nathan/raspi/tools/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian-x64/lib/gcc/arm-linux-gnueabihf/4.8.3/include-fixed -I/home/nathan/raspi/tools/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian-x64/arm-linux-gnueabihf/include -I/home/nathan/raspi/sysroot/usr/include -I/home/nathan/raspi/sysroot/usr/include/arm-linux-gnueabihf frame.h -o moc_frame.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_frame.h
compiler_uic_clean:
	-$(DEL_FILE) ui_frame.h
ui_frame.h: frame.ui
	/home/nathan/raspi/qt5/bin/uic frame.ui -o ui_frame.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: main.cpp frame.h \
		../raspi/qt5pi/include/QtWidgets/QMainWindow \
		../raspi/qt5pi/include/QtWidgets/qmainwindow.h \
		../raspi/qt5pi/include/QtWidgets/qwidget.h \
		../raspi/qt5pi/include/QtGui/qwindowdefs.h \
		../raspi/qt5pi/include/QtCore/qglobal.h \
		../raspi/qt5pi/include/QtCore/qconfig.h \
		../raspi/qt5pi/include/QtCore/qfeatures.h \
		../raspi/qt5pi/include/QtCore/qsystemdetection.h \
		../raspi/qt5pi/include/QtCore/qprocessordetection.h \
		../raspi/qt5pi/include/QtCore/qcompilerdetection.h \
		../raspi/qt5pi/include/QtCore/qtypeinfo.h \
		../raspi/qt5pi/include/QtCore/qtypetraits.h \
		../raspi/qt5pi/include/QtCore/qisenum.h \
		../raspi/qt5pi/include/QtCore/qsysinfo.h \
		../raspi/qt5pi/include/QtCore/qlogging.h \
		../raspi/qt5pi/include/QtCore/qflags.h \
		../raspi/qt5pi/include/QtCore/qatomic.h \
		../raspi/qt5pi/include/QtCore/qbasicatomic.h \
		../raspi/qt5pi/include/QtCore/qatomic_bootstrap.h \
		../raspi/qt5pi/include/QtCore/qgenericatomic.h \
		../raspi/qt5pi/include/QtCore/qatomic_cxx11.h \
		../raspi/qt5pi/include/QtCore/qatomic_gcc.h \
		../raspi/qt5pi/include/QtCore/qatomic_msvc.h \
		../raspi/qt5pi/include/QtCore/qatomic_armv7.h \
		../raspi/qt5pi/include/QtCore/qatomic_armv6.h \
		../raspi/qt5pi/include/QtCore/qatomic_armv5.h \
		../raspi/qt5pi/include/QtCore/qatomic_ia64.h \
		../raspi/qt5pi/include/QtCore/qatomic_x86.h \
		../raspi/qt5pi/include/QtCore/qatomic_unix.h \
		../raspi/qt5pi/include/QtCore/qglobalstatic.h \
		../raspi/qt5pi/include/QtCore/qmutex.h \
		../raspi/qt5pi/include/QtCore/qnumeric.h \
		../raspi/qt5pi/include/QtCore/qversiontagging.h \
		../raspi/qt5pi/include/QtCore/qobjectdefs.h \
		../raspi/qt5pi/include/QtCore/qnamespace.h \
		../raspi/qt5pi/include/QtCore/qobjectdefs_impl.h \
		../raspi/qt5pi/include/QtGui/qwindowdefs_win.h \
		../raspi/qt5pi/include/QtCore/qobject.h \
		../raspi/qt5pi/include/QtCore/qstring.h \
		../raspi/qt5pi/include/QtCore/qchar.h \
		../raspi/qt5pi/include/QtCore/qbytearray.h \
		../raspi/qt5pi/include/QtCore/qrefcount.h \
		../raspi/qt5pi/include/QtCore/qarraydata.h \
		../raspi/qt5pi/include/QtCore/qstringbuilder.h \
		../raspi/qt5pi/include/QtCore/qlist.h \
		../raspi/qt5pi/include/QtCore/qalgorithms.h \
		../raspi/qt5pi/include/QtCore/qiterator.h \
		../raspi/qt5pi/include/QtCore/qhashfunctions.h \
		../raspi/qt5pi/include/QtCore/qpair.h \
		../raspi/qt5pi/include/QtCore/qbytearraylist.h \
		../raspi/qt5pi/include/QtCore/qstringlist.h \
		../raspi/qt5pi/include/QtCore/qregexp.h \
		../raspi/qt5pi/include/QtCore/qstringmatcher.h \
		../raspi/qt5pi/include/QtCore/qcoreevent.h \
		../raspi/qt5pi/include/QtCore/qscopedpointer.h \
		../raspi/qt5pi/include/QtCore/qmetatype.h \
		../raspi/qt5pi/include/QtCore/qvarlengtharray.h \
		../raspi/qt5pi/include/QtCore/qcontainerfwd.h \
		../raspi/qt5pi/include/QtCore/qobject_impl.h \
		../raspi/qt5pi/include/QtCore/qmargins.h \
		../raspi/qt5pi/include/QtGui/qpaintdevice.h \
		../raspi/qt5pi/include/QtCore/qrect.h \
		../raspi/qt5pi/include/QtCore/qsize.h \
		../raspi/qt5pi/include/QtCore/qpoint.h \
		../raspi/qt5pi/include/QtGui/qpalette.h \
		../raspi/qt5pi/include/QtGui/qcolor.h \
		../raspi/qt5pi/include/QtGui/qrgb.h \
		../raspi/qt5pi/include/QtGui/qrgba64.h \
		../raspi/qt5pi/include/QtGui/qbrush.h \
		../raspi/qt5pi/include/QtCore/qvector.h \
		../raspi/qt5pi/include/QtGui/qmatrix.h \
		../raspi/qt5pi/include/QtGui/qpolygon.h \
		../raspi/qt5pi/include/QtGui/qregion.h \
		../raspi/qt5pi/include/QtCore/qdatastream.h \
		../raspi/qt5pi/include/QtCore/qiodevice.h \
		../raspi/qt5pi/include/QtCore/qline.h \
		../raspi/qt5pi/include/QtGui/qtransform.h \
		../raspi/qt5pi/include/QtGui/qpainterpath.h \
		../raspi/qt5pi/include/QtGui/qimage.h \
		../raspi/qt5pi/include/QtGui/qpixelformat.h \
		../raspi/qt5pi/include/QtGui/qpixmap.h \
		../raspi/qt5pi/include/QtCore/qsharedpointer.h \
		../raspi/qt5pi/include/QtCore/qshareddata.h \
		../raspi/qt5pi/include/QtCore/qhash.h \
		../raspi/qt5pi/include/QtCore/qsharedpointer_impl.h \
		../raspi/qt5pi/include/QtGui/qfont.h \
		../raspi/qt5pi/include/QtGui/qfontmetrics.h \
		../raspi/qt5pi/include/QtGui/qfontinfo.h \
		../raspi/qt5pi/include/QtWidgets/qsizepolicy.h \
		../raspi/qt5pi/include/QtGui/qcursor.h \
		../raspi/qt5pi/include/QtGui/qkeysequence.h \
		../raspi/qt5pi/include/QtGui/qevent.h \
		../raspi/qt5pi/include/QtCore/qvariant.h \
		../raspi/qt5pi/include/QtCore/qmap.h \
		../raspi/qt5pi/include/QtCore/qdebug.h \
		../raspi/qt5pi/include/QtCore/qtextstream.h \
		../raspi/qt5pi/include/QtCore/qlocale.h \
		../raspi/qt5pi/include/QtCore/qset.h \
		../raspi/qt5pi/include/QtCore/qcontiguouscache.h \
		../raspi/qt5pi/include/QtCore/qurl.h \
		../raspi/qt5pi/include/QtCore/qurlquery.h \
		../raspi/qt5pi/include/QtCore/qfile.h \
		../raspi/qt5pi/include/QtCore/qfiledevice.h \
		../raspi/qt5pi/include/QtGui/qvector2d.h \
		../raspi/qt5pi/include/QtGui/qtouchdevice.h \
		../raspi/qt5pi/include/QtWidgets/qtabwidget.h \
		../raspi/qt5pi/include/QtGui/qicon.h \
		../raspi/qt5pi/include/QtWidgets/QPushButton \
		../raspi/qt5pi/include/QtWidgets/qpushbutton.h \
		../raspi/qt5pi/include/QtWidgets/qabstractbutton.h \
		../raspi/qt5pi/include/QtWidgets/QApplication \
		../raspi/qt5pi/include/QtWidgets/qapplication.h \
		../raspi/qt5pi/include/QtCore/qcoreapplication.h \
		../raspi/qt5pi/include/QtCore/qeventloop.h \
		../raspi/qt5pi/include/QtWidgets/qdesktopwidget.h \
		../raspi/qt5pi/include/QtGui/qguiapplication.h \
		../raspi/qt5pi/include/QtGui/qinputmethod.h \
		../raspi/qt5pi/include/QtWidgets/QStyle \
		../raspi/qt5pi/include/QtWidgets/qstyle.h \
		../raspi/qt5pi/include/QtWidgets/QDesktopWidget
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

frame.o: frame.cpp frame.h \
		../raspi/qt5pi/include/QtWidgets/QMainWindow \
		../raspi/qt5pi/include/QtWidgets/qmainwindow.h \
		../raspi/qt5pi/include/QtWidgets/qwidget.h \
		../raspi/qt5pi/include/QtGui/qwindowdefs.h \
		../raspi/qt5pi/include/QtCore/qglobal.h \
		../raspi/qt5pi/include/QtCore/qconfig.h \
		../raspi/qt5pi/include/QtCore/qfeatures.h \
		../raspi/qt5pi/include/QtCore/qsystemdetection.h \
		../raspi/qt5pi/include/QtCore/qprocessordetection.h \
		../raspi/qt5pi/include/QtCore/qcompilerdetection.h \
		../raspi/qt5pi/include/QtCore/qtypeinfo.h \
		../raspi/qt5pi/include/QtCore/qtypetraits.h \
		../raspi/qt5pi/include/QtCore/qisenum.h \
		../raspi/qt5pi/include/QtCore/qsysinfo.h \
		../raspi/qt5pi/include/QtCore/qlogging.h \
		../raspi/qt5pi/include/QtCore/qflags.h \
		../raspi/qt5pi/include/QtCore/qatomic.h \
		../raspi/qt5pi/include/QtCore/qbasicatomic.h \
		../raspi/qt5pi/include/QtCore/qatomic_bootstrap.h \
		../raspi/qt5pi/include/QtCore/qgenericatomic.h \
		../raspi/qt5pi/include/QtCore/qatomic_cxx11.h \
		../raspi/qt5pi/include/QtCore/qatomic_gcc.h \
		../raspi/qt5pi/include/QtCore/qatomic_msvc.h \
		../raspi/qt5pi/include/QtCore/qatomic_armv7.h \
		../raspi/qt5pi/include/QtCore/qatomic_armv6.h \
		../raspi/qt5pi/include/QtCore/qatomic_armv5.h \
		../raspi/qt5pi/include/QtCore/qatomic_ia64.h \
		../raspi/qt5pi/include/QtCore/qatomic_x86.h \
		../raspi/qt5pi/include/QtCore/qatomic_unix.h \
		../raspi/qt5pi/include/QtCore/qglobalstatic.h \
		../raspi/qt5pi/include/QtCore/qmutex.h \
		../raspi/qt5pi/include/QtCore/qnumeric.h \
		../raspi/qt5pi/include/QtCore/qversiontagging.h \
		../raspi/qt5pi/include/QtCore/qobjectdefs.h \
		../raspi/qt5pi/include/QtCore/qnamespace.h \
		../raspi/qt5pi/include/QtCore/qobjectdefs_impl.h \
		../raspi/qt5pi/include/QtGui/qwindowdefs_win.h \
		../raspi/qt5pi/include/QtCore/qobject.h \
		../raspi/qt5pi/include/QtCore/qstring.h \
		../raspi/qt5pi/include/QtCore/qchar.h \
		../raspi/qt5pi/include/QtCore/qbytearray.h \
		../raspi/qt5pi/include/QtCore/qrefcount.h \
		../raspi/qt5pi/include/QtCore/qarraydata.h \
		../raspi/qt5pi/include/QtCore/qstringbuilder.h \
		../raspi/qt5pi/include/QtCore/qlist.h \
		../raspi/qt5pi/include/QtCore/qalgorithms.h \
		../raspi/qt5pi/include/QtCore/qiterator.h \
		../raspi/qt5pi/include/QtCore/qhashfunctions.h \
		../raspi/qt5pi/include/QtCore/qpair.h \
		../raspi/qt5pi/include/QtCore/qbytearraylist.h \
		../raspi/qt5pi/include/QtCore/qstringlist.h \
		../raspi/qt5pi/include/QtCore/qregexp.h \
		../raspi/qt5pi/include/QtCore/qstringmatcher.h \
		../raspi/qt5pi/include/QtCore/qcoreevent.h \
		../raspi/qt5pi/include/QtCore/qscopedpointer.h \
		../raspi/qt5pi/include/QtCore/qmetatype.h \
		../raspi/qt5pi/include/QtCore/qvarlengtharray.h \
		../raspi/qt5pi/include/QtCore/qcontainerfwd.h \
		../raspi/qt5pi/include/QtCore/qobject_impl.h \
		../raspi/qt5pi/include/QtCore/qmargins.h \
		../raspi/qt5pi/include/QtGui/qpaintdevice.h \
		../raspi/qt5pi/include/QtCore/qrect.h \
		../raspi/qt5pi/include/QtCore/qsize.h \
		../raspi/qt5pi/include/QtCore/qpoint.h \
		../raspi/qt5pi/include/QtGui/qpalette.h \
		../raspi/qt5pi/include/QtGui/qcolor.h \
		../raspi/qt5pi/include/QtGui/qrgb.h \
		../raspi/qt5pi/include/QtGui/qrgba64.h \
		../raspi/qt5pi/include/QtGui/qbrush.h \
		../raspi/qt5pi/include/QtCore/qvector.h \
		../raspi/qt5pi/include/QtGui/qmatrix.h \
		../raspi/qt5pi/include/QtGui/qpolygon.h \
		../raspi/qt5pi/include/QtGui/qregion.h \
		../raspi/qt5pi/include/QtCore/qdatastream.h \
		../raspi/qt5pi/include/QtCore/qiodevice.h \
		../raspi/qt5pi/include/QtCore/qline.h \
		../raspi/qt5pi/include/QtGui/qtransform.h \
		../raspi/qt5pi/include/QtGui/qpainterpath.h \
		../raspi/qt5pi/include/QtGui/qimage.h \
		../raspi/qt5pi/include/QtGui/qpixelformat.h \
		../raspi/qt5pi/include/QtGui/qpixmap.h \
		../raspi/qt5pi/include/QtCore/qsharedpointer.h \
		../raspi/qt5pi/include/QtCore/qshareddata.h \
		../raspi/qt5pi/include/QtCore/qhash.h \
		../raspi/qt5pi/include/QtCore/qsharedpointer_impl.h \
		../raspi/qt5pi/include/QtGui/qfont.h \
		../raspi/qt5pi/include/QtGui/qfontmetrics.h \
		../raspi/qt5pi/include/QtGui/qfontinfo.h \
		../raspi/qt5pi/include/QtWidgets/qsizepolicy.h \
		../raspi/qt5pi/include/QtGui/qcursor.h \
		../raspi/qt5pi/include/QtGui/qkeysequence.h \
		../raspi/qt5pi/include/QtGui/qevent.h \
		../raspi/qt5pi/include/QtCore/qvariant.h \
		../raspi/qt5pi/include/QtCore/qmap.h \
		../raspi/qt5pi/include/QtCore/qdebug.h \
		../raspi/qt5pi/include/QtCore/qtextstream.h \
		../raspi/qt5pi/include/QtCore/qlocale.h \
		../raspi/qt5pi/include/QtCore/qset.h \
		../raspi/qt5pi/include/QtCore/qcontiguouscache.h \
		../raspi/qt5pi/include/QtCore/qurl.h \
		../raspi/qt5pi/include/QtCore/qurlquery.h \
		../raspi/qt5pi/include/QtCore/qfile.h \
		../raspi/qt5pi/include/QtCore/qfiledevice.h \
		../raspi/qt5pi/include/QtGui/qvector2d.h \
		../raspi/qt5pi/include/QtGui/qtouchdevice.h \
		../raspi/qt5pi/include/QtWidgets/qtabwidget.h \
		../raspi/qt5pi/include/QtGui/qicon.h \
		../raspi/qt5pi/include/QtWidgets/QPushButton \
		../raspi/qt5pi/include/QtWidgets/qpushbutton.h \
		../raspi/qt5pi/include/QtWidgets/qabstractbutton.h \
		ui_frame.h \
		../raspi/qt5pi/include/QtCore/QCoreApplication \
		../raspi/qt5pi/include/QtCore/qcoreapplication.h \
		../raspi/qt5pi/include/QtCore/qeventloop.h \
		../raspi/qt5pi/include/QtCore/QString
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o frame.o frame.cpp

moc_frame.o: moc_frame.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_frame.o moc_frame.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

